#!/bin/bash

export DESKTOP_CORE_NAME="tabby"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v1.0.201
export DESKTOP_CORE_ORG="Eugeny"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/tabby/releases/download"

export DESKTOP_CORE_CHECKSUMS=(
  v1.0.201#darwin#arm64#7d92e635ca589f48366001b771edeafea88e86cb24b26cd35720ea2e4bdb8ca8
  v1.0.201#darwin#amd64#c77bd48aa525c8362ef73f62cd8c6c7c4f53fb1d1b75b0116622f1e4c7529140
)
