#!/bin/bash

export DESKTOP_CORE_NAME="tabby"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v1.0.201
export DESKTOP_CORE_ORG="Eugeny"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://github.com/${DESKTOP_CORE_ORG}/tabby/releases/download"

export DESKTOP_CORE_CHECKSUMS=(
  v1.0.201#darwin#arm64#9fa18ccd04bf1b7bed0311613c11c6b52f67f24193a211af92482f65ff745446
  v1.0.201#darwin#amd64#cbe42cf8ecc33b8e0c23849e2743256a8dcd1895c936b3d73d5ba96c5671bc6d
)
